"""Reproduce post hoc review aggregates from fixed, source-bound AI annotations.

No API requests, credential reads, raw-record edits or primary-score changes.
The semantic judgements are supplied data, not generated by this program.
"""

from pathlib import Path
import hashlib, json, math, statistics
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ITEMS = ["task_interpretation_0_2", "method_evidence_0_2", "explanation_alignment_0_2"]


def sha(data):
    return hashlib.sha256(data).hexdigest()


def canonical(value):
    return json.dumps(value, sort_keys=True, ensure_ascii=False).encode()


def validate_annotations(records, annotations, rubric_bytes, raw_bytes):
    if annotations["rubric_sha256"] != sha(rubric_bytes):
        raise ValueError("Review rubric changed; re-adjudication is required")
    if annotations["runs_jsonl_sha256"] != sha(raw_bytes):
        raise ValueError("Raw source changed; old annotations cannot be reused")
    reviewed = annotations["records"]
    source = {r["run_id"]: r for r in records}
    if len(source) != len(records) or len({r["run_id"] for r in reviewed}) != len(
        reviewed
    ):
        raise ValueError("Duplicate run identifier")
    if set(source) != {r["run_id"] for r in reviewed}:
        raise ValueError("Incomplete or extraneous review coverage")
    for a in reviewed:
        r = source[a["run_id"]]
        if a["record_sha256"] != sha(canonical(r)):
            raise ValueError("Review does not match complete source record")
        if any(a[k] != r[k] for k in ("phase", "condition", "question_id")):
            raise ValueError("Incorrect annotation metadata")
        if a["explanation"] != r["answer"]["explanation"]:
            raise ValueError("Explanation mismatch")
        if a["flagged_excerpt"] not in a["explanation"]:
            raise ValueError("Flagged prose excerpt is not verbatim")
        if a["prose_support_category"] not in (0, 1, 2):
            raise ValueError("Invalid prose category")
        if a["prose_support_category"] and not a["flagged_excerpt"]:
            raise ValueError("Flagged prose needs an excerpt")
        if not all(a[k] in (0, 1, 2) for k in ITEMS):
            raise ValueError("Invalid reasoning item")
        if not a["prose_rationale"] or not a["reasoning_rationale"]:
            raise ValueError("Missing judgement rationale")
        if len(a["calls"]) != len(r["tool_calls"]):
            raise ValueError("Missing tool-call judgement")
        for i, (c, t) in enumerate(zip(a["calls"], r["tool_calls"]), 1):
            injected = bool(t.get("injected"))
            if (
                c["call_index"] != i
                or c["arguments"] != t["arguments"]
                or c["tool"] != t["name"]
                or c["evidence_id"] != t["result"]["evidence_id"]
            ):
                raise ValueError("Tool-call alignment mismatch")
            if (
                c["injected"] != injected
                or c["eligible_selection"] != (not injected)
                or c["eligible_parameters"] != (not injected and t["name"] != "profile")
            ):
                raise ValueError("Incorrect denominator eligibility")
            if c["selection_correct"] not in (0, 1) or (
                c["parameters_correct"] not in (0, 1)
                if t["name"] != "profile"
                else c["parameters_correct"] is not None
            ):
                raise ValueError("Invalid tool judgement")
            if not c["rationale"]:
                raise ValueError("Missing call rationale")
    return reviewed


def dispersion(values):
    x = [float(v) for v in values if v is not None and math.isfinite(float(v))]
    n = len(x)
    mean = statistics.mean(x) if n else None
    var = statistics.variance(x) if n >= 2 else None
    sd = math.sqrt(var) if var is not None else None
    return {
        "n": n,
        "mean": mean,
        "sample_variance": var,
        "sample_sd": sd,
        "cv": sd / mean if sd is not None and mean is not None and mean > 0 else None,
    }


def main():
    out = ROOT / "outputs/study_v1/analysis"
    raw = (out.parent / "runs.jsonl").read_bytes()
    records = [json.loads(x) for x in raw.splitlines()]
    annotations = json.loads(
        (ROOT / "config/trace_review_annotations.json").read_text()
    )
    reviewed = validate_annotations(
        records,
        annotations,
        (ROOT / "documentation/TRACE_REVIEW_RUBRIC.md").read_bytes(),
        raw,
    )
    run_rows = []
    call_rows = []
    for a in reviewed:
        row = {
            k: a[k]
            for k in [
                "run_id",
                "phase",
                "condition",
                "question_id",
                "prose_support_category",
                *ITEMS,
                "prose_rationale",
                "flagged_excerpt",
                "reasoning_rationale",
            ]
        }
        row.update(
            kind="answerable" if a["question_id"].startswith("Q") else "adversarial",
            reasoning_total=sum(a[k] for k in ITEMS),
            prose_unsupported=a["prose_support_category"] == 2,
            prose_ambiguous=a["prose_support_category"] == 1,
            prose_flagged=a["prose_support_category"] > 0,
        )
        eligible = [c for c in a["calls"] if c["eligible_selection"]]
        row.update(
            eligible_tool_calls=len(eligible),
            all_calls_suitable=(
                all(c["selection_correct"] for c in eligible) if eligible else None
            ),
        )
        run_rows.append(row)
        for c in a["calls"]:
            call_rows.append(
                {
                    **{
                        k: row[k]
                        for k in ("run_id", "phase", "condition", "question_id", "kind")
                    },
                    **c,
                    "arguments": json.dumps(c["arguments"], sort_keys=True),
                    "issue_codes": ";".join(c["issue_codes"]),
                }
            )
    runs = pd.DataFrame(run_rows)
    calls = pd.DataFrame(call_rows)
    runs.to_csv(out / "posthoc_review_runs.csv", index=False)
    calls.to_csv(out / "posthoc_review_calls.csv", index=False)
    summaries = []
    for (phase, condition), base in runs.groupby(["phase", "condition"], sort=True):
        for kind in ("all", "answerable", "adversarial"):
            g = base if kind == "all" else base[base.kind == kind]
            if g.empty:
                continue
            c = calls[calls.run_id.isin(g.run_id)]
            sel = c[c.eligible_selection]
            param = c[c.eligible_parameters]
            summaries.append(
                {
                    "phase": phase,
                    "condition": condition,
                    "kind": kind,
                    "runs": len(g),
                    "prose_unsupported_n": int(g.prose_unsupported.sum()),
                    "prose_ambiguous_n": int(g.prose_ambiguous.sum()),
                    "prose_flagged_n": int(g.prose_flagged.sum()),
                    "reasoning_mean_0_6": float(g.reasoning_total.mean()),
                    "reasoning_median_0_6": float(g.reasoning_total.median()),
                    "reasoning_min_0_6": int(g.reasoning_total.min()),
                    "reasoning_max_0_6": int(g.reasoning_total.max()),
                    **{k + "_mean": float(g[k].mean()) for k in ITEMS},
                    "selection_correct_calls": int(sel.selection_correct.sum()),
                    "selection_eligible_calls": len(sel),
                    "parameter_correct_calls": int(param.parameters_correct.sum()),
                    "parameter_eligible_calls": len(param),
                    "runs_with_eligible_calls": int((g.eligible_tool_calls > 0).sum()),
                    "runs_without_eligible_calls": int(
                        (g.eligible_tool_calls == 0).sum()
                    ),
                    "all_calls_suitable_runs": int(g.all_calls_suitable.eq(True).sum()),
                }
            )
    summary = pd.DataFrame(summaries)
    summary.to_csv(out / "posthoc_review_summary.csv", index=False)
    primary = pd.read_csv(out / "run_scores.csv")
    if set(primary.run_id) != set(runs.run_id):
        raise ValueError("Primary scores and review inventory differ")
    variance = []
    numeric = []
    source = {r["run_id"]: r for r in records}
    for (condition, q), g in primary[primary.phase == "main"].groupby(
        ["condition", "question_id"], sort=True
    ):
        if len(g) != 5 or set(g.replication) != {1, 2, 3, 4, 5}:
            raise ValueError("Incomplete repeated-run group")
        row = {
            "condition": condition,
            "question_id": q,
            "runs": len(g),
            "successes": int(g.task_success.sum()),
        }
        for key, col in [
            ("success", "task_success"),
            ("latency_s", "latency_s"),
            ("cost_usd", "cost_usd"),
        ]:
            row.update({key + "_" + k: v for k, v in dispersion(g[col]).items()})
        variance.append(row)
        question = next(
            x
            for x in json.loads((out.parent / "manifest.json").read_text())["study"][
                "questions"
            ]
            if x["id"] == q
        )
        for field in question["fields"]:
            vals = []
            nulls = 0
            nonnumeric = 0
            for rid in g.run_id:
                value = {
                    c["field"]: c["value"] for c in source[rid]["answer"]["claims"]
                }.get(field)
                if value is None:
                    nulls += 1
                    continue
                try:
                    number = float(str(value).replace(",", ""))
                    if not math.isfinite(number):
                        raise ValueError()
                    vals.append(number)
                except (ValueError, TypeError):
                    nonnumeric += 1
            numeric.append(
                {
                    "condition": condition,
                    "question_id": q,
                    "field": field,
                    "task_kind": question["kind"],
                    "total_runs": len(g),
                    "null_or_missing": nulls,
                    "nonnumeric": nonnumeric,
                    **dispersion(vals),
                    "scope": "conditional on finite asserted values; numerical stability does not establish correctness",
                }
            )
    pd.DataFrame(variance).to_csv(out / "posthoc_variance.csv", index=False)
    pd.DataFrame(numeric).to_csv(out / "posthoc_numeric_variance.csv", index=False)
    receipt = {
        "status": "complete exploratory AI-assisted review",
        "review_version": annotations["review_version"],
        "review_date": annotations["review_date"],
        "reviewed_runs": len(runs),
        "reviewed_calls": len(calls),
        "prose_ratings_complete": int(runs.prose_support_category.notna().sum()),
        "reasoning_ratings_complete": int(runs[ITEMS].notna().all(axis=1).sum()),
        "primary_protocol_changed": False,
        "raw_source_sha256": sha(raw),
        "annotations_sha256": sha(
            (ROOT / "config/trace_review_annotations.json").read_bytes()
        ),
        "rubric_sha256": annotations["rubric_sha256"],
        "human_ratings": 0,
        "independent_raters": 0,
        "api_calls": 0,
        "limitations": [
            "Post hoc rubric and unblinded single AI-assisted reviewer",
            "No independent human adjudication or inter-rater reliability",
            "Semantic selection/parameter ratings share context and overlap",
            "Reproduction checks annotation bindings and arithmetic, not judgement validity",
        ],
    }
    (out / "posthoc_review_receipt.json").write_text(
        json.dumps(receipt, indent=2) + "\n"
    )
    print(summary[summary.kind == "all"].to_string(index=False))
    print(
        "Source bindings, coverage and denominators validated for",
        len(runs),
        "runs and",
        len(calls),
        "calls.",
    )


if __name__ == "__main__":
    main()
